services:
  app:
    container_name: appcontainer
    image: hoipranav/app:1.2
    network_mode: "appnetwork"
    ports:
      - 8501:8501

  web:
    container_name: apicontainer
    image: hoipranav/api:1.2
    network_mode: "appnetwork"
    ports:
      - 8081:8081